{% set name = "prettypyplot" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettypyplot-{{ version }}.tar.gz
  sha256: f668cfd9101e6ecb6ee2f6ab25cd5f65180f2a57e0bd63dd70cd6ed66c8edf9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - decorit >=0.2.0

test:
  imports:
    - prettypyplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/braniii/prettypyplot
  summary: Wrapper for matplotlib to generate publication-ready figures
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://braniii.gitlab.io/prettypyplot
  dev_url: https://gitlab.com/braniii/prettypyplot

extra:
  recipe-maintainers:
    - braniii
