{% set name = "prettypyplot" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prettypyplot-{{ version }}.tar.gz
  sha256: 77ed1d7d51634e617e0e1a320de6028420effa6daa498bba70d3c8728c79aa43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - decorit >=0.2.0
    - matplotlib-base
    - numpy
    - python >=3.6

test:
  imports:
    - prettypyplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/braniii/prettypyplot
  summary: Wrapper for matplotlib to generate publication-ready figures
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://braniii.gitlab.io/prettypyplot
  dev_url: https://gitlab.com/braniii/prettypyplot

extra:
  recipe-maintainers:
    - braniii
