{% set name = "prettypyplot" %}
{% set version = "0.13.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettypyplot-{{ version }}.tar.gz
  sha256: f81a8f721c555aafb9f63a69090ec535dbe0e1684076e06f184c4afa398d9278

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - decorit >=0.2.0

test:
  imports:
    - prettypyplot
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/braniii/prettypyplot
  summary: Wrapper for matplotlib to generate publication-ready figures
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://braniii.github.io/prettypyplot
  dev_url: https://github.com/braniii/prettypyplot

extra:
  recipe-maintainers:
    - braniii
